title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://tinarmengineering.github.io/docs

aux_links:
  Template Repo: https://github.com/tinarmengineering/docs
  LTC: https://app.ltc.tinarmengineering.com

logo: "https://avatars.githubusercontent.com/u/67412053?s=100"
