title: Linked Tool Chain Documentation
description: Documentation for Tin Arm Engineering's Linked Tool Chain
theme: just-the-docs

url: https://tinarmengineering.github.io/docs

aux_links_new_tab: true
aux_links:
  LTC:MotorTwin: https://app.ltc.tinarmengineering.com
  OpenAPI: https://api.ltc.tinarmengineering.com/docs/index.html


logo: "assets/ltc-logo.png"

plugins:
  - jekyll-jupyter-notebook

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.4.0"