title: Linked Tool Chain Documentation
description: Documentation for Tin Arm Engineering's Linked Tool Chain
theme: just-the-docs

url: https://tinarmengineering.github.io/docs

aux_links:
  Template Repo: https://github.com/tinarmengineering/docs
  LTC: https://app.ltc.tinarmengineering.com

logo: "https://avatars.githubusercontent.com/u/67412053?s=100"

plugins:
  - jekyll-jupyter-notebook